name: "HerosDeath"
main: "at.grevinelveck.herosdeath.Herosdeath"
version: "1.2"


commands:
   Revive:
      description: This command brings a player back to life
      usage: /Revive [player]
permissions:
    HerosDeath.*:
        description: Gives controll over life and death
        children:
            HerosDeath.Revive: true
            HerosDeath.Ghost: true
            HerosDeath.Haunt: true
    HerosDeath.Revive:
        description: Allows you to kick a user
        default: op
    HerosDeath.Ghost:
        description: Allows you to ban a user
        default: op
    HerosDeath.Haunt:
        description: Allows you to kill a user
        default: op