name: "CharonsFerry"
main: "at.grevinelveck.charonsferry.CharonsFerry"
version: "1.2"


commands:
   Ferry:
      description: This command brings the ferryman to your beck and call
      usage: /Ferry [Command] [player]
permissions:
    CharonsFerry.*:
        description: Gives controll over life and death
        children:
            CharonsFerry.Revive: true
            CharonsFerry.Ghost: true
            CharonsFerry.Haunt: true
            CharonsFerry.Poltergeist: true
            CharonsFerry.Boon: true
    CharonsFerry.Revive:
        description: Allows you to revive a user
        default: op
    CharonsFerry.Ghost:
        description: Allows you to "die" without the messy parts.
        default: op
    CharonsFerry.Haunt:
        description: Allows you to tp to a player.
        default: op
    CheronsFerry.Poltergeist:
        descriptoin: Allows a ghost to be interact with its inviroment.
        default: op
    CheronsFerry.Boon:
        descriptoin: Allows a user to see if he he will revive apon death
        default: op