name: "HerosDeath"
main: "at.grevinelveck.herosdeath.HerosDeath"
version: "1.2"


commands:
   Revive:
      description: This command brings a player back to life
      usage: /Revive [player]
      usage: /Ghost [player]
      usage: /Haunt [player]
permissions:
    HerosDeath.*:
        description: Gives controll over life and death
        children:
            HerosDeath.Revive: true
            HerosDeath.Ghost: true
            HerosDeath.Haunt: true
    HerosDeath.Revive:
        description: Allows you to revive a user
        default: op
    HerosDeath.Ghost:
        description: Allows you to "die" without the messy parts.
        default: op
    HerosDeath.Haunt:
        description: Allows you to tp to a player.
        default: op